# Generated by Django 3.2.4 on 2021-07-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('star', models.IntegerField()),
                ('comments', models.TextField()),
            ],
        ),
    ]
