# Generated by Django 3.2.4 on 2021-07-27 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_pic', models.ImageField(upload_to='images/')),
                ('date_created', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('course_title', models.CharField(max_length=20)),
                ('course_content', models.CharField(max_length=50)),
                ('course_price', models.CharField(max_length=10)),
                ('course_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.team')),
                ('course_tutor_pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_picture', to='new.team')),
            ],
        ),
    ]
