# Generated by Django 3.2.4 on 2021-07-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0006_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='date_created',
            field=models.DateField(),
        ),
    ]
