# Generated by Django 3.2.4 on 2021-07-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0008_auto_20210727_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
